### ISSUE TITLE
Is the OVA on the official wesite available ?? 

### ISSUE THREAD

**Issue by ArturLorek** [sexilog/sexilog#51]
It seems the OVA appliance that used to be available on the website (http://files.sexilog.fr/SexiLog.ova) is not anymore.
Would you please advise whether there is an alternative download location available ??

Thank you kindly

**Comment by rschitz** [comment]
Hi Arthur, thanks for your support. We had a storage issue few days ago and forgot to update some links. It's fixed now, please try again and let us know.

**Comment by ArturLorek** [comment]
Thank you greatly for you swift response.
I have just tried, but to no avail.
I will try again later, maybe it needs some time ;)

![image](https://user-images.githubusercontent.com/33265194/149821946-06dc2f12-eb1d-4a23-a0e1-b38cd65bdb24.png)

**Comment by rschitz** [comment]
right, should be ok this time

**Comment by ochompsky** [comment]
almost one year later and the download link is still broken lmao

**Comment by rschitz** [comment]
![image](https://user-images.githubusercontent.com/8385646/206142872-3a0b9ed0-d63b-4463-8074-2644d3dca345.png)

**Comment by rschitz** [comment]
it's still working fine.
BTW, are you using SexiLog for VMware purpose or for something else?

**Comment by ochompsky** [comment]
wget works but not browser, the file is not served over ssl.  and yeah i was thinking for vmware but am leaning towards something dockerized instead of a separate appliance, just experimenting

`Mixed Content: The site at 'https://www.sexilog.fr/' was loaded over a secure connection, but the file at 'http://files.sexilog.fr/SexiLog.ova' was loaded over an insecure connection. This file should be served over HTTPS. This download has been blocked. See https://blog.chromium.org/2020/02/protecting-users-from-insecure.html for more details.`
